### ISSUE TITLE
[Feature Request] Option for three colums: total, previous, current

### ISSUE THREAD

**Issue by x51mon** [iamjustkoi/StudyTimeStats#10]
I think it'd be cool to have an option to display three values. So one can have e.g. total time, previous week and current week.
That way it'd be possible to compare the current week with the previous one and see the total time growing at the same time

**Comment by iamjustkoi** [comment]
Oh yeah, I can definitely see that being a nice option to have. It might need a pretty decent rework of how some stuff is setup, to be honest, but I can try and find some time to work on this in the near future, hopefully!

For the time being, though, you can also add multiple macros to a single stat's output, if you want.
It might not be the exact style you're looking for, unfortunately, but if you wanted to have the total and previous times displayed on the left stat, for instance, you could do something like this:

> (General)
> Total Title: `Total/Previous %range`
> (Advanced)
> Total Text Output: `%total_hrs / %last_cal_hrs`

Small Preview:
![preview](https://user-images.githubusercontent.com/97048143/180606682-da2fc06e-8a27-4212-a888-7ce58ac24d15.png)

**Comment by darlopvil** [comment]
Came here to exactly talk about this feature. I'd also like to compare my last week time with the actual one.

btw, maybe there's a little bug inside the “about” tab. Nothing happens when clicking on the GitHub, releases, changelog words. Came here through the review on AnkiWeb button.

**Comment by iamjustkoi** [comment]
> btw, maybe there's a little bug inside the “about” tab. Nothing happens when clicking on the GitHub, releases, changelog words. Came here through the review on AnkiWeb button.

Oh shoot, thanks for the report! Will move that to #13.

> Came here to exactly talk about this feature. I'd also like to compare my last week time with the actual one.

Hopefully I can make some room to work on this more in the near future! I've been able to get some nice UI tests working, so the next step is mainly just making some changes to the internals, I think. 
Either way, will defs be trying to schedule this for the next major release!

**Comment by iamjustkoi** [comment]
Wanted to give a quick update: 

Sorry for the delay! This has been pushed back quite a bit since my schedule's been a pretty tight, recently, to be honest. I want to try and make some time to work on it more this winter, though. Will have to see what happens.

**Comment by iamjustkoi** [comment]
Should be added in the most recent release! 
Thanks for writing in!
