### ISSUE TITLE
Lost settings.

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#11]
**Bug/Issue Description**
A short description of the issue.

This latest update undoes all changed settings.

**Comment by iamjustkoi** [comment]
> This latest update undoes all changed settings.

Shoot, as in they're not saving or all previous settings were overwritten after updating but you can still save now?
Either way, sorry you're running into the issue!

**Comment by iamjustkoi** [comment]
Oh, looks this might be the same issue as #12, can check it out further.
