### ISSUE TITLE
Known Issue: Crash on Startup

### ISSUE THREAD

**Issue by iamjustkoi** [iamjustkoi/StudyTimeStats#14]
**Bug/Issue Description**
Crash on boot after recent update (v1.3.5).

**To Reproduce**
Steps to reproduce:
1. Enabled the add-on
2. Open Anki

**Additional Context**
Reported on AnkiWeb, may have to do with some faulty auto-imports.

Leaving this up here just in case there's any follow up, but hopefully this should be fixed in the most recent release (v1.3.6).

**Comment by RazgrizR** [comment]
The add-on crashing upon startup still occurs even after v.1.3.6 update, here is what my error message looks like:

'⁨Study Time Stats⁩' 読み込みの際:
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 8, in <module>
    from .src import main
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1247171202\src\main.py", line 11, in <module>
    from .config import ANKI_VERSION, TimeStatsConfigManager
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1247171202\src\config.py", line 16, in <module>
    def _reformat_conf(config: dict[str: Any]):
TypeError: 'type' object is not subscriptable

Thank you for the add-on and hopefully this info helps

**Comment by iamjustkoi** [comment]
Should be fixed with the most recent release, now! Thanks for the report!

**Comment by iamjustkoi** [comment]
Oh boy, okay, now the last release should actually fix it! My bad, got a little overexcited there.
