### ISSUE TITLE
[Feature Request] Review Count option

### ISSUE THREAD

**Issue by MarvNC** [iamjustkoi/StudyTimeStats#16]
Would be cool if there was an option to show counts for both hours and reviews. If this is already a thing then my apologies.

**Comment by iamjustkoi** [comment]
Oh yeah, sounds like a nice addition to me! Was thinking I might try to add a few more stats in, anyway, all things considered.

Will defs try to see if I can add something like this in within the next release and/or upcoming releases, thanks for the suggestion!

**Comment by iamjustkoi** [comment]
Should be added in the most recent release (v2.0.0)! 
Thanks again!
