### ISSUE TITLE
Study End Time for Review and Learn Cards

### ISSUE THREAD

**Issue by JeremiaWilliams** [iamjustkoi/StudyTimeStats#18]
**Feature Description**
I think it could be helpful to have the add-on estimate how much more studying is left to do for the current day's learning & review cards to be completed.

This would not need to include new cards, as that can vary based on learning steps per deck.

**Alternatives Considered**
https://ankiweb.net/shared/info/1097423555
[Relevant function](https://github.com/carlos1172/ProgressBarTimeLeft/blob/main/reviewer_progress_bar.py#L269-L372): `updatePB`, line 372 where var `ETA` is assigned.

**Additional context**
That add-on has it as a progress bar at the top of the screen during reviews. I find this distracting, and think it would be great to just have it only on the home screen, as you do. Example from that add-on:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/74698406/229934458-b78a2a18-2369-4119-8cc8-4a12071fb5e2.png">

**Comment by iamjustkoi** [comment]
Sure sure, sounds interesting! Shouldn't be too much extra with everything else in the works for the upcoming release, anyway. Will try to see if I can fit this in, or at least something close to it! 

For the time being: I actually made a personal extension to the more overview stats add-on (https://ankiweb.net/shared/info/738807903) that does something similar to this a long while ago. 
Maybe you'd wanna check that out and see how it goes for you, too:
[more_overview_stats_ext.zip](https://github.com/iamjustkoi/StudyTimeStats/files/11157553/more_overview_stats_ext.zip)
(put the unzipped file in your (Windows) %APPDATA%/Anki2/addons21 folder (e.g. C:\Users\justkoi\AppData\Roaming\Anki2\addons21\more_overview_stats_ext))

It might not work 100%, though, fair warning. I pretty much just patched it together one morning, so it's a bit scrappy, but it pretty much tells you how many cards (including new card counts using the preset step counts) are left for a deck, but only in each decks' overview page, so not on the main screen, unfortunately.

**Comment by iamjustkoi** [comment]
Should be added in the most recent release (v2.0.0)! 
Thanks again!
