### ISSUE TITLE
Styling and Dark Mode

### ISSUE THREAD

**Issue by JeremiaWilliams** [iamjustkoi/StudyTimeStats#19]
**Potential Issues**
When I switch between dark and light mode, I have to change the colors in the settings to increase contrast to make the text legible.

**Feature Description**
An option to display the stats just like they are on the home screen. So it could say:

```
Studied X cards in Y hours this week (Zs/card)
Studied A cards in B hours total (Cs/card)
```

This would be right below the normal text to maintain consistency and location of information. Here is a photo of the home screen with the relevant text:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/74698406/229935792-65f3a1b9-6151-42f3-83ee-64518e2f73d5.png">

**Alternatives Considered**
Color picker for dark mode and light mode separately.

**Comment by iamjustkoi** [comment]
Should be added in the most recent release (v2.0.0)! 
Thanks, again, for the request!
