### ISSUE TITLE
spacing between information.

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#2]
I have an ultrawide monitor.
See how the information looks on them. I believe you have to limit it to the center of the screen.

Anki 800x600
![image](https://user-images.githubusercontent.com/42243532/176999459-a939451b-c894-465d-b0c8-6a457ce61c7f.png)

Monitor Ultrawide
![image](https://user-images.githubusercontent.com/42243532/176999480-411079b8-1e60-4cd3-be05-5728e091acfa.png)

**Comment by iamjustkoi** [comment]
Scheduled this for the next update. Thanks for reporting!
