### ISSUE TITLE
Option Page doesn`t show correctly

### ISSUE THREAD

**Issue by darlopvil** [iamjustkoi/StudyTimeStats#24]
**Bug/Issue Description**
What`s up. 

Problem here is about the stats that can be set in the addon page. I cannot check any option, as this check symbol doesn't appear itself. You can do the left-click in the small boxes, but nothing shows (the check symbol).
Also, tab names appear very close one from other.

**To Reproduce**
Steps to reproduce:
1. Go to Tools > Addons > Study Time Stats

**Screenshots/Visuals**
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/b8558b9e-7366-4869-9876-b4bb523ac75c)
![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/37135e62-97b4-417d-ad55-ea240e9d8294)

**System/Debug Info**
    
    Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.19041
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-05-27 16:30:59
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Japanese ['1344485230', 2023-05-23T20:15, 'None', mod]
    Anki Day of Rest ['1776268610', 2023-02-25T20:00, 'None', '']
    AnkiConnect ['2055492159', 2023-04-11T19:20, 'None', '']
    Editor Live Preview ['1960039667', 2023-03-24T17:35, 'None', '']
    Image Editor ['307397307', 2022-09-08T06:09, 'None', '']
    OpenInExternalEditorRenameDuplicate for ImageAudioVideo ['1560623518', 2023-03-19T18:33, 'None', mod]
    PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-24T02:59, 'None', '']
    RefoldEase ['819023663', 2023-02-22T12:27, 'None', mod]
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
    Study Time Stats ['1247171202', 2023-05-26T19:39, 'None', '']
    True Retention ['613684242', 2017-11-19T21:43, 'None', '']
    Wiktionary ['2087444887', 2023-05-22T11:11, 'None', mod]
    Yomichan Forvo Server ['580654285', 2022-10-26T07:06, 'None', '']
    anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ['858591644', 2022-07-31T13:26, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2022-03-13T11:51, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1247171202 1344485230 1560623518 1771074083 1776268610 1960039667 2055492159 2087444887 307397307 580654285 613684242 805891399 819023663 858591644 876946123
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    More Decks Stats and Time Left ['1556734708', 2022-10-09T14:05, 'None', '']
    More Overview Stats ['2116130837', 2022-09-16T19:56, 'None', '']

**Additional Context**
Due to this abnormal behavior, nothing can be set nor adjustable as desired.

Thank you for your hard work 🙏

**Comment by iamjustkoi** [comment]
Sorry this's shown up for you! Defs weird behavior.
Since you're running the Qt6 version, it's also strange that the tabs look like Qt5 tabs, too.
May have something to do with Anki's compatibility shims? Will try to see what I can do. 
Thanks for the report!

> Slightly different but related problem is present on Mac. The menu can be interacted with completely normally, it's strictly a visual issue.

Shoot, I think this might be a separate issue, too. Could be a problem with the file paths.
Either way, moved it to a new thread for the time being (#27).

**Comment by darlopvil** [comment]
> try removing the add-on, restarting Anki, checking your database (Tools -> Check Database), and reinstalling the add-on and see if that might help out?

Done, doesn't work. 

> Otherwise, I might be able to do more with the add-on's meta.json file (Tools -> Add-ons -> Study Time Stats -> View Files), if you wanna try and upload that, too.

Sure, here you have the file:
https://anonfiles.com/I4Df68u1zd/meta_json

**Comment by darlopvil** [comment]
Hello! I've found what caused the problem. Now it's solved.

I realized this issue didn't only happen with this addon of yours, but with every other I had installed (you can check in the first message, the huge number of addons installed). I had to downgrade the version of Anki until 2.1.63 to view everything correctly:

![imagen](https://github.com/iamjustkoi/StudyTimeStats/assets/60988792/0cfa97ca-8cc6-4868-8114-995f5063dc54)

This is only a workaround obviously, I'm not a big fan of keeping old versions. I prefer to have it updated to the latest version.

**Comment by iamjustkoi** [comment]
Ope, good to hear! 

Wonder if it's something to do with Anki install, or some corrupted files, or something along those lines?

Either way, happy you were able to get it somewhat solved for the time being! 
Thanks for the report!
