### ISSUE TITLE
%eta_hrs only considers subdecks

### ISSUE THREAD

**Issue by JeremiaWilliams** [iamjustkoi/StudyTimeStats#25]
**Bug/Issue Description**
The %eta_hrs only seems to account for subdecks.

**To Reproduce**
Steps to reproduce:
1. Create a new, empty deck.
2. Create a subdeck.
3. Add a card to the subdeck.
4. The overview of the parent deck is correct
5. The overview of the subdeck is incorrect

**Screenshots/Visuals**
<img width="465" alt="image" src="https://github.com/iamjustkoi/StudyTimeStats/assets/74698406/90a1f4a9-7db8-40eb-8f67-f729a32574c6">
<img width="465" alt="image" src="https://github.com/iamjustkoi/StudyTimeStats/assets/74698406/74e48a0d-d9b1-48bb-bae5-aaf71733a15f">

**Comment by iamjustkoi** [comment]
Oh, whoops, really appreciate the report!
Was able to fix this real quick, should be scheduled for the next release.
