### ISSUE TITLE
Wrong/stuck times

### ISSUE THREAD

**Issue by Sterilisator** [iamjustkoi/StudyTimeStats#26]
**Bug/Issue Description**
Since the last update total and week counter are stuck and display same time regardless of subdeck.
Also total time got reduced from 200+ hours to the 75,28hrs it is currently stuck on.

Reinstalling does not help, reverting back to old version fixes the issue

**System/Debug Info**
{
    "traceback": "Debugging",
    "debug": {
        "amboss": {
            "version": "0.6.8",
            "channel": "download",
            "language": "de",
            "stage": "production",
            "package": "0amboss_addon",
            "env": {
                "AMBOSS_GRAPHQL_URI": "https://content-gateway.eu.production.amboss.com",
                "AMBOSS_RESTPHRASE_URI": "https://anki.eu.production.amboss.com/v1/anki/",
                "AMBOSS_LIBRARY_URI": "https://next.amboss.com/de/article"
            },
            "config": {
                "enablePopupDefinitions": true,
                "enablePopupDefinitonsOnQuestions": true,
                "enableArticleViewer": true,
                "hotkeyOpenNextPopup": "Shift+F",
                "hotkeyOpenPreviousPopup": "Shift+D",
                "hotkeyClosePopup": "Shift+Esc",
                "hotkeyToggleSidePanel": "Shift+A",
                "styleColorHighlights": "#0fcad4"
            }
        },
        "anki": {
            "version": "2.1.63 (f356f177)",
            "flavor": "standard",
            "python": "3.9.15",
            "qt": "6.4.0",
            "pyqt": "6.4.0",
            "platform": "Windows 10",
            "frozen": true,
            "addonsLoaded": true,
            "scheduler": "2",
            "env": {
                "ANKI_NOVERIFYSSL": null,
                "ANKI_BASE": null,
                "ANKI_NOHIGHDPI": null,
                "ANKI_SOFTWAREOPENGL": null,
                "ANKI_WEBSCALE": null,
                "DEBUG": null,
                "QT_XCB_FORCE_SOFTWARE_OPENGL": null,
                "QT_OPENGL": null
            },
            "locale": [
                "German_Austria",
                "1252"
            ],
            "cacert": "C:\\Program Files\\Anki\\lib\\certifi\\cacert.pem",
            "sslVersion": "OpenSSL 1.1.1s  1 Nov 2022"
        },
        "reviewer": null,
        "addons": [
            "AMBOSS add-on",
            "Speed Focus Mode auto-alert auto-reveal auto-answer (deaktiviert)",
            "Study Time Stats",
            "Image Occlusion Enhanced",
            "More Decks Stats and Time Left",
            "Progress Bar original (deaktiviert)",
            "Dark title bars for windows",
            "Puppy Reinforcement",
            "Show total review count in main screen",
            "Review Heatmap",
            "Customize Keyboard Shortcuts",
            "Image Editor",
            "Colorful Tags  Hierarchical Tags",
            "True Retention (deaktiviert)",
            "Multiple Choice"
        ]
    },
    "message": ""
}

**Comment by iamjustkoi** [comment]
Based on some tests, it seems like this and #23 might be related, going to go ahead and merge them, for now.
Either way, thanks for the report!
