### ISSUE TITLE
Missing Images for MacOS and Linux

### ISSUE THREAD

**Issue by iamjustkoi** [iamjustkoi/StudyTimeStats#27]
> This problem is present with both "Native" style and "Anki" style rendering.

(Appears to happen for MacOS, might also show up on other Linux-based systems)

**Bug/Issue Description**
> 1. Direction buttons do not render correctly
> 2. Arrange buttons do not render
> 3. Macro buttons do not render
> 4. Delete buttons do not render
> 5. Add Stat button does not render
> 6. Code buttons do not render

**Screenshots/Visuals**
> <img width="928" alt="image" src="https://github.com/iamjustkoi/StudyTimeStats/assets/74698406/02c486ac-839c-46f1-bc2c-556688fbb15c">

_Originally posted by @JeremiaWilliams in https://github.com/iamjustkoi/StudyTimeStats/issues/24#issuecomment-1565683178_

**Comment by x51mon** [comment]
Unfortunately for me the issue persists. Manjaro Linux with KDE Plasma, AddOn Version is 2.0.4
![Screenshot_20230601_122623](https://github.com/iamjustkoi/StudyTimeStats/assets/67149510/24c7a4e0-a14d-4c85-95ab-6d45ab42cc9b)

**Comment by iamjustkoi** [comment]
> Unfortunately for me the issue persists.

Shoot, sorry.

May need to create a debug patch to retrieve some extra logs, but I might also try and setup a new VM to see if I can reproduce the issue, on my end, again.

Either way, thanks for reporting it! Will see what I can do as soon as I can.

**Comment by iamjustkoi** [comment]
Wellp, was actually a really easy fix. 
I, uh, used the wrong slash character for the image paths in a single line of code...

But yeah, should be fixed with latest recent release (2.0.5)!
