### ISSUE TITLE
Sometimes "Congratulations!" Page Displays Double Time Stats

### ISSUE THREAD

**Issue by RobertBKaiser** [iamjustkoi/StudyTimeStats#3]
<img width="524" alt="Screen Shot 2022-07-02 at 7 38 11 AM" src="https://user-images.githubusercontent.com/9099907/176999438-0f6728bf-fc8b-4dee-b320-869296cba0ea.png">
I can reproduce the bug by clicking on a finished deck which pops up the congratulations page, going back to the overview screen, and clicking on a **different** completed deck. That always displays double stats as seen in the picture for me.
If I do the exact same thing, but instead click on the same deck it goes away.

**Comment by iamjustkoi** [comment]
Should be resolved in the next update. Thanks for reporting!
