### ISSUE TITLE
Color styling that changes with the Anki theme

### ISSUE THREAD

**Issue by Hap-lorhini** [iamjustkoi/StudyTimeStats#33]
Howdy,

I would love to see colour styling that changes based on whether Anki is in light or dark theme.
Maybe I am in the minority, but I do like to have Anki follow my systems theme, which changes between day and night.
Currently, I have set the colours in the addon to work with both, but if they could change with the theme, I would prefer the aesthetic.

H.

**Comment by iamjustkoi** [comment]
Hey! Sorry about the delay.
Funny enough, it's actually possible to change the color based on the current theme/mode in Anki using the add-on's HTML code section! (You can find it using the Stat View's little `</>` button in the bottom right.)

You'd pretty much just want to add something like the following to the code:
```html
    <div id="<custom-id>" style="font-weight: bold;">{{Output}}</div>
    <script>
            // Javascript
            // Get the element using its id
            let output = document.getElementById('<custom-id>'); 
            // If Anki's document body has the "night-mode" class, set the output's color accordingly:
            if (document.body.classList.contains('night-mode')) {{{{
                // Dark Theme (Comment)
                output.style.color = '<hexadecimal/rgb/named color>';
            }}}} else {{{{
                // Light Theme (Comment)
                output.style.color = '<e.g. #fffff/rgb(255,255,255)/white>'; 
            }}}}
    </script>
```

In-context, it might look something like this:
```html
<div class="{{CellClass}}">
    <div id="title-a" style="color: {{TitleColor}};">{{Title}}</div>
    <div id="output-a" style="font-weight: bold;">{{Output}}</div>
    <script>
            let title = document.getElementById('title-a');
            let output = document.getElementById('output-a');
            if (document.body.classList.contains('night-mode')) {{{{
                // Dark Theme
                title.style.color = 'white';
                output.style.color = '#1d233c';
            }}}} else {{{{
                // Light Theme
                title.style.color = 'black';
                output.style.color = 'rgb(151, 222, 255)'; 
            }}}}
    </script>
</div>
```

Pretty much, you can replace the two `<custom-id>` labels with whatever you want and add a color to either of the two spots in the '' quotations marks, under the `Dark Theme` and `Light Theme` comments. 

(*It's also important to place the `<script>` element after any `<div id='<custom-id>'>` elements, and use 4 `{` characters whenever you'd want to use 1 in Javascript, just in case.*)

Anyway, hope that might help out a bit! I could see about making this a bit less complex in the future if there's still some more demand for it! 

Wish you the best! 😄
