### ISSUE TITLE
Exclude deleted cards from history

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#4]
**Issue/Bug Description**

It could have a heatmap-like button that restricts the math to only existing cards.
I recreated my deck and they are totally egg cards, but they are being considered cards that I no longer have.

**Screenshots/Visuals**

Main page
![image](https://user-images.githubusercontent.com/42243532/177012637-8714113b-fe1c-49f8-9a35-34586e4dac59.png)

When you finish all the cards
![image](https://user-images.githubusercontent.com/42243532/177012660-d44ebbcd-bdda-46ec-8b9f-42e251697635.png)

Heatmap Parameter
![image](https://user-images.githubusercontent.com/42243532/177012821-0ea87582-73d2-4aaa-bfc5-2bc440a569da.png)

**Comment by cjdduarte** [comment]
it's just a suggestion. could be a check.

**Comment by iamjustkoi** [comment]
> it's just a suggestion. could be a check.

Oh yeah, could see that being useful, actually. Will look into it for the next update, thanks!
