### ISSUE TITLE
Update addon to work with 23.10

### ISSUE THREAD

**Issue by shmuelsash** [iamjustkoi/StudyTimeStats#40]
**Bug/Issue Description**
Update to work with new anki program version

**Screenshots/Visuals**
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/35056305/b5afbd00-026c-478e-8e6d-d8f3b740811d)

**System/Debug Info**
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-14 12:28:52

When loading Study Time Stats:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 8, in <module>
    from .src import toolbar
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1247171202\src\toolbar.py", line 12, in <module>
    from .options import TimeStatsOptionsDialog
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1247171202\src\options.py", line 41, in <module>
    from ..res.ui.cell_item import Ui_CellWidget
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1247171202\res\ui\cell_item.py", line 11, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Additional Context**
Any other context that might seem important.

**Comment by AustinHasten** [comment]
I had luck resolving this by replacing "PyQt5" with "PyQt6" in these files:

cell_item.py
macro_dialog.py
options_dialog.py

And then using the script found here (https://stackoverflow.com/a/72658216/3261260) to replace all of the Qt5 enums with the Qt6 versions. No crashes on startup or when opening the configuration menu.

**Comment by iamjustkoi** [comment]
> I had luck resolving this by replacing "PyQt5" with "PyQt6" in these files:
> 
> cell_item.py macro_dialog.py options_dialog.py
> 
> And then using the script found here (https://stackoverflow.com/a/72658216/3261260) to replace all of the Qt5 enums with the Qt6 versions. No crashes on startup or when opening the configuration menu.

Ope, thanks for the workaround! Can mention it for #39 and will try and implement the fix as soon as I can! :D

**Comment by jbuddha** [comment]
Same issue

**Comment by iamjustkoi** [comment]
Should be fixed with the most recent release (v2.1.0)! 

Thanks again everyone for helping, reporting, and submitting fixes for this issue! 
Wish everyone the best, and happy studies! ^^
