### ISSUE TITLE
Study Time

### ISSUE THREAD

**Issue by ghost** [iamjustkoi/StudyTimeStats#42]
Fantastic addition! I'm really enjoying it! I have a quick question as a non-technical person, as I couldn't find the answer in the description or elsewhere: Could you kindly explain how the estimated study time is calculated in simple terms? Thanks a lot!

**Comment by iamjustkoi** [comment]
Oh, sure! Sorry about having a bit of a late reply!

> Could you kindly explain how the estimated study time is calculated in simple terms?

As a gist, as far as I remember what I coded, is that it takes all of the reviews for whatever decks are enabled or currently visible, finds the average time per review, then multiplies that by the number of estimated reviews (pretty basic, largely based on each deck's settings).

Hope that helps a bit and thanks for the question!
