### ISSUE TITLE
Possible to release update via AnkiWeb?

### ISSUE THREAD

**Issue by kk-min** [iamjustkoi/StudyTimeStats#46]
Hi, came here due to the infamous PyQt5 start up error and saw that it has been fixed [here](https://github.com/iamjustkoi/StudyTimeStats/pull/43), but I noticed that an official release for this hasn't been uploaded to the [AnkiWeb page](https://ankiweb.net/shared/info/1247171202). 

Is there any plans to release it via AnkiWeb as well, as I prefer getting updates within Anki? Thank you!

**Comment by iamjustkoi** [comment]
Hey! Sorry the delay and thanks for asking! 

> any plans to release it via AnkiWeb as well

Yep! Right now I'm just having to merge some changes from the public repo with my local one, but currently just stuck on a small bug I caused related to checking Anki versions, then I wanna double check everything and should be good to go (next release has a few fixes that I wanted to push out at the same time, pretty much).

Right now I'm hoping to release an update this weekend, if not within the next couple days.

Either way, thanks again, appreciate the Q, and I'll go ahead and leave this open until the next release is fully finished and uploaded! ^^

**Comment by tommai78101** [comment]
As an added bonus, you can pin issues, so you can highlight them and redirect visitors to that pinned issue when they are browsing this repository.

**Comment by iamjustkoi** [comment]
Just released via AnkiWeb right now (v2.1.0)! Thanks again, and happy travels! 😄
