### ISSUE TITLE
Average Daily Reviews

### ISSUE THREAD

**Issue by CHA0S-KING** [iamjustkoi/StudyTimeStats#51]
Hey Koi,

It's me again, I was wondering whether you could add a macro for average reviews done per day? I am not sure if it already exists but based on the other macro formats, I tried it out and it was unsuccessful.

![Avg Daily Reviews](https://github.com/iamjustkoi/StudyTimeStats/assets/159644053/9ca69c62-47a9-414a-a596-9dee99c827d2)

Cheers!

**Comment by iamjustkoi** [comment]
Oh, shoot, yeah, that sounds like a nice macro to add in!

I wish I had more time on my hands so I could tackle this and some of the smaller feature requests others have posted, but either way I'd love to try and add this in the next chance I get!

Appreciate the suggestion and thanks for, again, posting! :D

**Comment by iamjustkoi** [comment]
Added in the latest release! Thanks everyone for the recommendations and PR's! ^^
