### ISSUE TITLE
Multiple uses of %day_avg_hrs give different results based on order

### ISSUE THREAD

**Issue by TommyAmberson** [iamjustkoi/StudyTimeStats#52]
**Bug/Issue Description**
When there are more than one widgets that use %day_avg_hrs, only the first one seems accurate. I can rearrange them and they change values based on the order.

**To Reproduce**
Steps to reproduce:
1. from the default settings change both widgets 'Output' to '%range_hrs / %days = %day_avg_hrs' (or just '%day_avg_hrs' but this way you can see that one of them is wrong)
2. Click on 'OK' and note the values
3. Go back to the settings and reorder the widgets
4. The times have completely changed

**Screenshots/Visuals**
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/53712733/84094457-3937-4b92-89c5-53fcd8ab1c2e)
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/53712733/3982b72b-a322-4a82-84c4-2d5ab133d8c9)
reorder
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/53712733/e68e586b-573f-4b65-bf73-70cdad1e862d)
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/53712733/79e1a06a-eea6-4e2f-94c6-8ccbadef804c)

**System/Debug Info**
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.5.0-15-generic-x86_64-with-glibc2.35

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T08:34, 'None', '']
Anki Simulator ['817108664', 2023-11-06T11:26, 'None', '']
Batch Editing ['291119185', 2023-10-25T18:38, 'None', '']
FSRS4Anki Helper ['759844606', 2024-02-18T03:32, 'None', mod]
More Overview Stats 21 ['738807903', 2021-07-30T13:13, 'None', '']
Study Time Stats ['1247171202', 2024-02-05T08:03, 'None', '']

===IDs of active AnkiWeb add-ons===
1247171202 291119185 738807903 759844606 817108664 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Fastbar- with nightmode support ['46611790', 2023-06-27T05:47, 'None', '']
Set Card Ease ['1387847178', 2022-12-26T02:44, 'None', mod]

**Additional Context**

**Comment by TommyAmberson** [comment]
It seems to use the range of the first '%day_avg_hrs' instead of the correct range given in the options

**Comment by iamjustkoi** [comment]
Should be fixed in the latest release! Thanks again for reporting and submitting the pull requests! :D
