### ISSUE TITLE
Viewing order

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#7]
Is it possible for the add-on information to appear before the heatmap?

**Screenshots/Visuals**

![image](https://user-images.githubusercontent.com/42243532/177045817-e41a5b0e-e99a-48cb-a9cd-bf64cd9fec8b.png)

**made in paint**
![image](https://user-images.githubusercontent.com/42243532/177045933-ba1602d7-ad34-43d9-9d1e-b357c1d552c2.png)

**System/Debug Info:**
You can get this from Anki in Help -> About -> Copy Debug Info,

**Additional context**
Any other context that might seem important to the issue.

**Comment by iamjustkoi** [comment]
> Is it possible for the add-on information to appear before the heatmap?
It might be, but I'll have to look more into how add-ons get loaded in Anki first, probs. 
Will see if I can maybe make this an option in the near future, though!

**Comment by madmaximux** [comment]
If it helps, this addon is able to render above the heatmap:

https://github.com/cjdduarte/MDS_Time_Left/blob/master/mds_time_left.py

**Comment by iamjustkoi** [comment]
Small update: I didn't really think about this until now, but it kind of looks like this also has a bit to do with how each add-on's appending its elements to the main window, actually. I can probs look into changing how that works a bit more and control where stuff's getting placed using that, too, though!

I might be able to get this done for in next update, or do something with a bit more customization on top of that. 
Will see!

**Comment by iamjustkoi** [comment]
The add-on's append method's been updated for the most recent release. Thanks for writing in!

**Comment by madmaximux** [comment]
> The add-on's append method's been updated for the most recent release. Thanks for writing in!

It's working great! Thank You!
