### ISSUE TITLE
Parameterize the 2 fields

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#8]
**Feature Description**
Could you leave the 2 fields parameterizable?
I would like to compare the current week with the previous week.

![image](https://user-images.githubusercontent.com/42243532/178075423-ac1cd53d-c9c8-4740-9913-c202d84d7775.png)

**Comment by iamjustkoi** [comment]
> **Feature Description**
> Could you leave the 2 fields parameterizable?
> I would like to compare the current week with the previous week.

Huh, yeah, that sounds pretty interesting actually!
I might have to edit a few things to have it work pretty smoothly, I think, but I can probs push a smaller update to give access to some more variables, for the time being, at least. With that, it'd probably be some text macros you can use in the titles/labels, though, until I'm able to work on and release the more significant stuff.

Funny enough, I was actually strongly considering adding some historical stat options to the UI, already! When I do, I might be able to make them a bit more dynamic too, though. Will try and see what I can do! Thanks for posting!

**Comment by iamjustkoi** [comment]
Had to rework a lot of stuff to implement the smaller changes, so I ended up just taking more time and pushing out a larger update, instead! Thanks again and hope you enjoy!

**Comment by cjdduarte** [comment]
Exclent
