### ISSUE TITLE
spacing between information 2

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#9]
**Bug/Issue Description**
After the last update, the problem returned. ☹️☹️

**Screenshots/Visuals**
![image](https://user-images.githubusercontent.com/42243532/178116113-e3c312ef-c542-47cd-813a-03941731a51f.png)

**Comment by iamjustkoi** [comment]
Whoops! Should be fixed now, thanks for reporting!
